[server]
headless = true
enableCORS = false
enableXsrfProtection = true
port = 8501

[theme]
primaryColor = "#667eea"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f5f7fa"
textColor = "#000000"
